import { Toaster } from "sonner";
import "./globals.css";
import { Metadata } from "next";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Suspense>
          <Toaster />
          {children}
        </Suspense>
      </body>
    </html>
  );
}
